"""
Make the branch column longer

Copyright (C) 2020 Kunal Mehta <legoktm@member.fsf.org>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Revision ID: ea4834de64e9
Revises: a2452f842414
Create Date: 2020-12-23 22:21:39.481753
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea4834de64e9'
down_revision = 'a2452f842414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'repositories', 'branch',
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.String(length=80),
        existing_nullable=False
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'repositories', 'branch',
        existing_type=sa.String(length=80),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False
    )
